// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // シンプルな構成にするためにドキュメントサイドバーを定義
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'pandoc',
      label: 'pandoc',
    },
    {
      type: 'category',
      label: 'FlatsPlus',
      items: [
        {
          type: 'autogenerated',
          dirName: 'flatsplus', // docs/flatsplus配下を自動でサイドバーに追加
        }
      ],
    },
    {
      type: 'category',
      label: 'Original',
      items: [
        {
          type: 'autogenerated',
          dirName: 'original', // docs/original配下を自動でサイドバーに追加
        }
      ],
    }
  ],

  // 必要に応じて追加のサイドバーを定義できます
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
